[env]
TERM = "alacritty"

[font]
size = 14

[font.glyph_offset]
y = 1

[font.normal]
family = "MesloLGL Nerd Font"
# family = "JetBrainsMonoNL Nerd Font Mono"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
opacity = 1.0

[colors.primary]
background = "#ffffff"
foreground = "#000000"
